module.exports={

    test:{
        "Estado": any,
        "Primer nombre del usuario": any,
        "Segundo nombre del usuario": any,
        "Primer apellido del usuario": any,
        "Segundo apellido del usuario": any,
        "Tipo de Identificación del usuario": any,
        "Número de Identificación del usuario": any,
        "Fecha de nacimiento": any,
        "Sexo": any,
        "Régimen de afiliación AL SGSS": any,
        "Código de la EPS o de la entidad territorial": any,
        "Código pertenencia étnica": any,
        "Grupo poblacional": any,
        "Municipio  de residencia": any,
        "número telefónico del paciente (incluyendo a familiares y cuidadores)": any,
        "Fecha de afiliación a la EPS que registra": any,
        "Código de la IPS donde se hace seguimiento al usuario": any,
        "Fecha de ingreso al programa de nefroporteccion dentro de la EPS que reporta": any,
        "El usuario tiene diagnóstico confirmado de Hipertensión Arterial -HTA (CIE-10 con códigos entre I10-I159)": any,
        "Fecha de diagnostico de la Hipertension Arterial": any,
        "Costo HTA durante el período de reporte.": any,
        "El usuario tiene diagnóstico confirmado de Diabetes Mellitus- DM (CIE-10 con códigos entre E10-E149; O24-O249; P702)": any,
        "Fecha de diagnostico de la Diabetes Mellitus": any,
        "Costo DM durante el período de reporte.": any,
        "Etiología de la ERC": any,
        "Peso (kg)": any,
        "Talla (cm)": any,
        "Tensión arterial sistólica (mm de Hg)": any,
        "Tensión arterial diastólica (mm de Hg)": any,
        "Creatinina en sangre (mg/dl)": any,
        "Fecha de última Creatinina": any,
        "Hemoglobina Glicosilada (%)": any,
        "Fecha de última Hemoglobina Glicosilada": any,
        "Albuminuria": any,
        "Fecha de la última Albuminuria": any,
        "Relación Albuminuria/Creatinuria (mg/g)": any,
        "Fecha de la última Albuminuria/Creatinuria": any,
        "Colesterol total (mg/dl)": any,
        "Fecha de la último Colesterol total": any,
        "HDL (mg/dl)": any,
        "Fecha de la último HDL": any,
        "LDL (mg/dl)": any,
        "Fecha del último LDL": any,
        "PTH (pg/ml)": any,
        "Fecha de la última PTH": any,
        "Tasa de filtración glomerular estimada (TFGe) según Cockroft-Gault (en adultos) o Swhartz (en menores de 18 años) o FFR estimada mediante el calculo del KrU": any,
        "El usuario recibe Inhibidor de la Enzima convertidora de angiotensina (IECA)  a la fecha de corte": any,
        "El usuario recibe Antagonista de los receptores de angiotensina II (ARA II) a la fecha de corte": any,
        "El usuario tiene diagnóstico de enfermedad renal crónica en cualquier de sus estadios.": any,
        "Estadio de la ERC": any,
        "Fecha de diagnóstico de ERC estadio 5 (Solo aplica si marco la opción 5 de la pregunta anterior):": any,
        "La persona se encuentra en un programa de atención de ERC (renoprotección, nefroprotección, protección renal, prediálisis)": any,
        "TFG a la fecha, en que el usuario inicio la primera terapia de reemplazo renal -TRR": any,
        "Modo de Inicio de la Terapia de Reemplazo Renal (primera TRR)": any,
        "Fecha en que se inicio la terapia de reemplazo renal que recibe el usuario en el momento de la fecha de corte. Sí el Trasplante es la terapia reportada, esta Fecha se refiere a la Fecha de trasplante.": any,
        "Fecha de Ingreso a la Unidad Renal Actual que le presta el servicio en el momento de la fecha de corte, en cualquier modalidad de terapia dialítica (Unidad Actual).": any,
        "Hemodiálisis (HD)": any,
        "Dosis de diálisis (Kt/V) single pool": any,
        "Costo total de la hemodiálisis HD durante el período de reporte.": any,
        "Diálisis peritoneal (DP)": any,
        "Dosis de diálisis (Kt/V) dpd. KTV/dpd:  de máximo cuatro meses de antigüedad contados a partir de la fecha de corte": any,
        "Numero de horas de dialisis": any,
        "Peritonitis": any,
        "Costo DP durante el período de reporte.": any,
        "Vacuna Hepatitis B": any,
        "Registre la fecha de diagnóstico de la infección por Hepatitis B, si el usuario la ha presentado.": any,
        "Registre la fecha de diagnóstico de la infección por Hepatitis C, si el usuario la ha presentado.": any,
        "Terapia no Dialítica para ERC estadio 5  (también llamada tratamiento médico de nefroproteción)": any,
        "Costo de la terapia ERC estadio 5 con tratamiento médico": any,
        "Hemoglobina (g/dl) (Solo aplica para personas con ERC DE 3 a 5)": any,
        "Albúmina Sérica (g/dl)(Solo aplica para personas con ERC DE 3 a 5)": any,
        "Fósforo (P) mg/dl (Solo aplica para personas con ERC DE 3 a 5)": any,
        "Valoración Clínica inicial por nefrología  a personas ERC5 en diálisis o tratamiento medico, en relación con la posibilidad de trasplante renal": any,
        "¿Se reportó cáncer activo en los últimos 12 meses, como contraindicación para el transplante renal, en la valoración de nefrología?": any,
        "¿Se reportó infección crónica o activa no tratada o no controlada hasta en los últimos tres meses antes de la fecha de corte, como contraindicación para el transplante renal, en la valoración de nefrología?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología que el paciente NO ha manifestado  su deseo de trasplantarse?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología que el paciente presenta esperanza de vida menor o igual a 6 meses?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología que el paciente presenta potenciales limitaciones al autocuidado y adherencia al tratamiento post trasplante?": any,
        "¿Se reportó enfermedad cardiaca, cerebrovascular o vascular periférica, como contraindicación para el transplante renal, en la valoración de nefrología?": any,
        "¿Se reportó  infección por el VIH, como contraindicación para el transplante renal, en la valoración de nefrología?": any,
        "¿Se reportó  infección por el VHC, como contraindicación para el transplante renal, en la valoración de nefrología?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología, que el paciente presenta enfermedad inmunológica activa los últimos tres meses antes de la fecha de corte?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología, que el paciente presenta enfermedad pulmonar crónica?": any,
        "¿Se reportó como contraindicación para el transplante renal, en la valoración de nefrología, que el paciente presenta otras enfermedades crónicas?": any,
        "Fecha de Ingreso a lista de espera para la realización del trasplante": any,
        "Registre el código de la IPS donde está en lista de espera": any,
        "¿El usuario ha recibido trasplante renal?": any,
        "Código de la EPS que realizó el trasplante": any,
        "Código de la IPS o Grupo de trasplante, que realizó el trasplante": any,
        "Tipo de donante": any,
        "Costo del trasplante": any,
        "¿El usuario ha presentado alguna complicación relacionada con el trasplante renal?": any,
        "Fecha de diagnóstico si ha presentado infección por Citomegalovirus": any,
        "Fecha de diagnóstico si ha presentado infección por hongos": any,
        "Fecha de diagnóstico si ha presentado infección por tuberculosis": any,
        "Fecha de diagnóstico si ha presentado alguna complicación vascular": any,
        "Fecha de diagnóstico si ha presentado alguna complicación urológica": any,
        "Fecha de diagnóstico si ha presentado alguna complicación herida quirúrgica": any,
        "Fecha del primer diagnóstico de cáncer": any,
        "Cuantos médicamentos inmunosupresores se formularon para el manejo en este último corte": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido  metilprednisolona": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido azatioprina": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido ciclosporina": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido micofenolato": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido tacrolimus": any,
        "En algún momento, desde el último reporte hasta el reporte actual ha recibido prednisona": any,
        "En tratamiento inmunosupresor ha recibido Medicamento NO POS (medicamento 1)": any,
        "En tratamiento inmunosupresor ha recibido Medicamento NO POS (medicamento 2)": any,
        "En tratamiento inmunosupresor ha recibido Medicamento NO POS (medicamento 3)": any,
        "¿Cuantos episodios de rechazo agudo en los últimos 12 meses al trasplante, confirmado por biopsia, ha presentado el usuario?": any,
        "Fecha del primer rechazo del injerto": any,
        "Fecha de retorno a diálisis": any,
        "Número de trasplantes renales que ha recibido": any,
        "Costo de la terapia postrasplante": any,
        "Tiempo de prestación de servicios": any,
        "Costo Total": any,
        "Código de la EPS de origen": any,
        "Novedad con respecto al reporte anterior": any,
        "Causa de Muerte": any,
        "Fecha de muerte": any,
        "Código único de identificación (BDUA, BDEX, PVS):": any,
        "Fecha de corte del reporte": any
    }



}